apiVersion: v1
kind: Pod
metadata:
  name: dind-escape-attempt-using-sock
spec:
  restartPolicy: Never
  containers:
    - name: dind-escape-attempt-using-sock
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'crictl -r unix:///custom/containerd/containerd.sock images; sleep infinity']
