apiVersion: v1
kind: Pod
metadata:
  name: find-aws-credentials
spec:
  restartPolicy: Never
  containers:
  - name: find-aws-credentials
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'grep aws_access_key_id ~/.aws/credentials; fgrep secretaccesskey somefile.txt; grep hello file.txt; grep aws_secret_access_key config.txt; find / -name .aws/credentials; mlocate .aws/credentials; locate secrets.txt']
