apiVersion: v1
kind: Pod
metadata:
  name: search-private-keys-and-passwords
spec:
  restartPolicy: Never
  containers:
  - name: search-private-keys-and-passwords
    image: angelrita/base-ubuntu:latest
    command: ['sh']
    args: ['-c', 'find / -name id_rsa; grep "BEGIN RSA PRIVATE KEY" ~/.ssh/id_rsa; find /home -name id_ed25519; egrep "BEGIN OPENSSH PRIVATE KEY" ~/.ssh/id_ed25519; fgrep "BEGIN PRIVATE KEY" ~/.ssh/id_ecdsa']
