apiVersion: v1
kind: Pod
metadata:
  name: dump-memory-utilities
spec:
  restartPolicy: Never
  containers:
  - name: dump-memory-utilities
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'gcore 1; sleep infinity']
