apiVersion: v1
kind: Pod
metadata:
  name: local-account-password-binary-execution
spec:
  restartPolicy: Never
  containers:
  - name: local-account-password-binary-execution
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'passwd; sleep infinity']
