apiVersion: v1
kind: Pod
metadata:
  name: log-file-symlink-to-null
spec:
  restartPolicy: Never
  containers:
  - name: log-file-symlink-to-null
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ["-c", "cp /bin/bash /tmp/testbash; ./tmp/testbash -c 'ln -sf /dev/null /var/log/syslog; sleep infinity'"]
