apiVersion: v1
kind: Pod
metadata:
  name: network-traffic-capture-via-cap-net-raw
spec:
  restartPolicy: Never
  containers:
  - name: network-traffic-capture-via-cap-net-raw
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', "tcpdump -i eth0 -w /tmp/capture.pcap; cp /bin/bash /tmp/testbash; setcap cap_net_raw+ep /tmp/testbash; sudo -u test /tmp/testbash; sleep infinity"]