apiVersion: v1
kind: Pod
metadata:
  name: network-utility-executed
spec:
  restartPolicy: Never
  containers:
  - name: network-utility-executed
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'tcpdump -i eth0; sleep infinity']
