apiVersion: v1
kind: Pod
metadata:
  name: process-execution-from-memory
spec:
  restartPolicy: Never
  containers:
  - name: process-execution-from-memory
    image: angelrita/memfd-exec:latest
    args: ['-c', '/proc/self/exe /bin/sh; sleep infinity']