apiVersion: v1
kind: Pod
metadata:
  name: apache-httpd-private-configs-access
spec:
  containers:
    - name: apache-httpd-private-configs-access
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir -p /etc/apache2/; echo "writing to htapassword" >> /etc/apache2/.htpasswd; cat /etc/apache2/.htpasswd; sleep infinity']
