apiVersion: v1
kind: Pod
metadata:
  name: appsecrets-read
spec:
  containers:
    - name: appsecrets-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir -p /etc/secrets/; echo "writing to htapassword" >> /etc/secrets/secret.json; cat  /etc/secrets/secret.json; sleep infinity']
