apiVersion: v1
kind: Pod
metadata:
  name: cicd-apps-config-read
spec:
  containers:
    - name: cicd-apps-config-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
