apiVersion: v1
kind: Pod
metadata:
  name: container-registry-package-manager-credentials-read
spec:
  containers:
    - name: container-registry-package-manager-credentials-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
