apiVersion: v1
kind: Pod
metadata:
  name: container-registry-package-manager-credentials-read
spec:
  restartPolicy: Never
  containers:
    - name: container-registry-package-manager-credentials-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir -p /.docker/; echo "writing to test" >> /.docker/config.json; cat /.docker/config.json; sleep infinity']
