apiVersion: v1
kind: Pod
metadata:
  name: delete-system-logs
spec:
  containers:
    - name: delete-system-logs
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
