apiVersion: v1
kind: Pod
metadata:
  name: dynamic-linker-configuration-modified
spec:
  restartPolicy: Never
  containers:
    - name: dynamic-linker-configuration-modified
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'echo "#include /etc/ld.so.conf.d/*.conf" >  /etc/ld.so.conf.d/test.conf;rm /etc/ld.so.conf.d/test.conf; sleep infinity']