apiVersion: v1
kind: Pod
metadata:
  name: dynamic-linker-configuration-modified
spec:
  containers:
    - name: dynamic-linker-configuration-modified
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
