apiVersion: v1
kind: Pod
metadata:
  name: git-and-ssh-credentials-read
spec:
  containers:
    - name: git-and-ssh-credentials-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
