apiVersion: v1
kind: Pod
metadata:
  name: iac-artifacts-read
spec:
  restartPolicy: Never
  containers:
    - name: iac-artifacts-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir -p /etc/ansible/; echo "test" >> /etc/ansible/inventory.ini; cat /etc/ansible/inventory.ini; sleep infinity']
