apiVersion: v1
kind: Pod
metadata:
  name: k8s-serviceaccount-secrets-read
spec:
  containers:
    - name: k8s-serviceaccount-secrets-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir -p /var/run/secrets/kubernetes.io/serviceaccount/; echo "writing to token" >> /var/run/secrets/kubernetes.io/serviceaccount/token; cat /var/run/secrets/kubernetes.io/serviceaccount/token; sleep infinity']  
