apiVersion: v1
kind: Pod
metadata:
  name: k8s-serviceaccount-secrets-read
spec:
  containers:
    - name: k8s-serviceaccount-secrets-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
