apiVersion: v1
kind: Pod
metadata:
  name: k8s-cloud-provider-secrets-read
spec:
  restartPolicy: Never
  containers:
    - name: k8s-cloud-provider-secrets-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir - p /.aws/; echo "writing to test" >> /.aws/credentials; cat /.aws/credentials; sleep infinity']