apiVersion: v1
kind: Pod
metadata:
  name: kernel-module-modified
spec:
  restartPolicy: Never
  containers:
    - name: kernel-module-modified
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir /lib/modules/; cp memfd-exec /lib/modules/; sleep infinity']
