apiVersion: v1
kind: Pod
metadata:
  name: local-credentials-modified
spec:
  containers:
    - name: local-credentials-modified
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'cat /etc/passwd; sleep infinity']