apiVersion: v1
kind: Pod
metadata:
  name: nsswitch-configuration-modified
spec:
  containers:
    - name: nsswitch-configuration-modified
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'echo "#nssswitch file appended" >> nssswi.conf; cp nssswi.conf /etc/nsswitch.conf; sleep infinity']
