apiVersion: v1
kind: Pod
metadata:
  name: overwrite-entrypoint
spec:
  containers:
    - name: overwrite-entrypoint
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'echo "Hello, world!" > /proc/self/fd/1; sleep infinity']