apiVersion: v1
kind: Pod
metadata:
  name: pam-modified
spec:
  containers:
    - name: pam-modified
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'cp memfd-exec /etc/pam.d/; echo "#rc.local modified" >> /etc/pam.conf']
