apiVersion: v1
kind: Pod
metadata:
  name: rc-scripts-modified
spec:
  containers:
    - name: rc-scripts-modified
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'echo "#rc.local modified" > /etc/rc.local']
