apiVersion: v1
kind: Pod
metadata:
  name: read-from-proc-file-system
spec:
  restartPolicy: Never
  containers:
    - name: read-from-proc-file-system
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'cat /proc/meminfo; sleep infinity']