apiVersion: v1
kind: Pod
metadata:
  name: redis-sandbox-escape
spec:
  containers:
    - name: redis-sandbox-escape
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
