apiVersion: v1
kind: Pod
metadata:
  name: release-agent-modification
spec:
  containers:
    - name: release-agent-modification
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
