apiVersion: v1
kind: Pod
metadata:
  name: runc-modification
spec:
  containers:
    - name: runc-modification
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'cp /usr/bin/bash /usr/bin/runc; sleep infinity']
