apiVersion: v1
kind: Pod
metadata:
  name: shell-history-deletion
spec:
  containers:
    - name: shell-history-deletion
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
