apiVersion: v1
kind: Pod
metadata:
  name: shell-history-deletion
spec:
  restartPolicy: Never
  containers:
    - name: shell-history-deletion
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'echo "# temp bash history" > ~/.bash_history; rm ~/.bash_history; sleep infinity']
