apiVersion: v1
kind: Pod
metadata:
  name: ssh-config-write
spec:
  containers:
    - name: ssh-config-write
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir /root/.prng; echo "#test config" > /root/.prng/test.config; sleep infinity']
