apiVersion: v1
kind: Pod
metadata:
  name: ssh-authorized-keys-modification
spec:
  containers:
    - name: ssh-authorized-keys-modification
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
