apiVersion: v1
kind: Pod
metadata:
  name: ssh-authorized-keys-modification
spec:
  restartPolicy: Never
  containers:
    - name: ssh-authorized-keys-modification
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir /root/.ssh; echo "ssh-rsa test_rsa_key root@puppetserver" > /root/.ssh/authorized_keys; sleep infinity']
