apiVersion: v1
kind: Pod
metadata:
  name: ssl-certificate-tampering
spec:
  containers:
    - name: ssl-certificate-tampering
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
