apiVersion: v1
kind: Pod
metadata:
  name: ssl-certificate-tampering
spec:
  containers:
    - name: ssl-certificate-tampering
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir /etc/ssl/certs -p; echo "#test config" > /etc/ssl/certs/test.cert; sleep infinity']
