apiVersion: v1
kind: Pod
metadata:
  name: sudoers-policy-modified
spec:
  restartPolicy: Never
  containers:
    - name: sudoers-policy-modified
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'echo "#test config" > /etc/sudoers; sleep infinity']
