apiVersion: v1
kind: Pod
metadata:
  name: systemd-modification
spec:
  containers:
    - name: systemd-modification
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'cp memfd-exec /lib/systemd/system; sleep infinity']
