apiVersion: v1
kind: Pod
metadata:
  name: tls-keys-and-lets-encrypt-secrets-read
spec:
  containers:
    - name: tls-keys-and-lets-encrypt-secrets-read
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir -p /etc/letsencrypt/live/; echo "writing to privkey.pem" >> /etc/letsencrypt/live/privkey.pem; cat /etc/letsencrypt/live/privkey.pem; sleep infinity']
