apiVersion: v1
kind: Pod
metadata:
  name: udev-modification
spec:
  containers:
    - name: udev-modification
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'mkdir /etc/udev/rules.d -p; echo "#test rules" > /etc/udev/rules.d/test.rules; sleep infinity']
