apiVersion: v1
kind: Pod
metadata:
  name: basic-interactive-reconnaissance
spec:
  restartPolicy: Never
  containers:
  - name: basic-interactive-reconnaissance
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'whoami; id; uname -a; sleep infinity']
