apiVersion: v1
kind: Pod
metadata:
  name: privilege-escalation-via-suid-binary-execution
spec:
  restartPolicy: Never
  containers:
  - name: privilege-escalation-via-suid-binary-execution
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'sudo -u test bash -c passwd; sleep infinity']
