apiVersion: v1
kind: Pod
metadata:
  name: privilege-escalation-via-process-capabilities
spec:
  restartPolicy: Never
  containers:
  - name: privilege-escalation-via-process-capabilities
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'cp /bin/bash /tmp/testbash; setcap cap_setgid,cap_setuid+ep /tmp/testbash; /tmp/testbash; sudo -u test /tmp/testbash -c whoami; sleep infinity']
