apiVersion: v1
kind: Pod
metadata:
  name: nc-reverse-sh
spec:
  containers:
  - name: nc-reverse-sh
    image: angelrita/nc-reverse-sh:latest
    #imagePullPolicy: Never
    ports:
    - containerPort: 4444

