apiVersion: v1
kind: Pod
metadata:
  name: cryptominer-execution-v2
spec:
  restartPolicy: Never
  containers:
  - name: cryptominer-execution-v2
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'modprobe msr allow_writes=on']