apiVersion: v1
kind: Pod
metadata:
  name: process-hidden-using-mount-hidepid
spec:
  restartPolicy: Never
  containers:
  - name: process-hidden-using-mount-hidepid
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'mount -o remount,hidepid=2 /proc']
