apiVersion: v1
kind: Pod
metadata:
  name: base-ubuntu
spec:
  containers:
  - name: base-ubuntu
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'sleep infinity']
    securityContext:
      privileged: true
