apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner-test
spec:
  selector:
    matchLabels:
      app: miner-test
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: miner-test
    spec:
      dnsConfig:
        nameservers:
          - 8.8.8.8
      containers:
      - name: miner-test
        image: miningcontainers/xmrig:latest
