apiVersion: qualys.com/v1
kind: FimPolicy
metadata:
 name: monitor-file-open
spec:
 base-policy: "file-open"
 action: "audit"
 monitor-paths:
  - "/home/"
  - "/dev/shm/"
  - "/etc/cron"
  - "/etc/crontab"
  - "/etc/crontabs/"
  - "/etc/gshadow/"
  - "/etc/ld.so.conf"
  - "/etc/ld.so.conf.d"
  - "/etc/ld.so.preload"
#  - "/etc/nsswitch.conf"
  - "/etc/pam.conf"
  - "/etc/pam.d/"
  - "/etc/passwd/"
  - "/etc/pki/"
  - "/etc/rc.common"
  - "/etc/rc.local"
  - "/etc/shadow/"
  - "/etc/ssl/certs/"
  - "/etc/sudoers"
  - "/etc/systemd/system/"
  - "/etc/udev/rules.d/"
  - "/lib/modules/"
  - "/lib/systemd/system/"
  - "/lib/udev/rules.d/"
  - "/proc/self/fd/1"
  - "/root/.config/"
  - "/root/.kube/config"
  - "/root/.prng/"
  - "/root/.ssh/"
  - "/run/udev/rules.d/"
  - "/sys/fs/cgroup"
  - "/sys/module/msr/parameters/allow_writes"
  - "/tmp/cgrp/release_agent"
  - "/tmp/cgrp/x/notify_on_release"
  - "/usr/bin/docker-runc"
  - "/usr/bin/runc"
#  - "/usr/lib/modules/"
#  - "/usr/lib/systemd/system/"
#  - "/usr/lib/udev/rules.d/"
#  - "/usr/lib/x86_64-linux-gnu/"
  - "/usr/local/lib/udev/rules.d/"
  - "/usr/sbin/runc"
  - "/var/log/auth.log"
  - "/var/log/boot.log"
  - "/var/log/btmp"
  - "/var/log/faillog"
  - "/var/log/kern.log"
  - "/var/log/lastlog"
  - "/var/log/messages"
  - "/var/log/secure"
  - "/var/log/syslog"
  - "/var/log/wtmp"
  - "/var/run/secrets/eks.amazonaws.com/serviceaccount/"
  - "/var/run/utmp"
  - "/var/spool/cron/"