apiVersion: qualys.com/v1
kind: FimPolicy
metadata:
 name: monitor-file-write
spec:
 base-policy: "file-write"
 action: "audit"
 monitor-paths:
  - "/tmp/"
  - "/home/"
  - "/dev/shm/"
  - "/dev/pts/"
  - "/etc/cron"
  - "/etc/crontab"
  - "/etc/crontabs/"
  - "/etc/gshadow/"
  - "/etc/ld.so.conf"
  - "/etc/ld.so.preload"
  - "/etc/ld.so.conf.d/"
  - "/etc/nsswitch.conf"
  - "/etc/pam.conf"
  - "/etc/pam.d/"
  - "/etc/passwd/"
  - "/etc/pki/"
  - "/etc/rc.common"
  - "/etc/rc.local"
  - "/etc/shadow/"
  - "/etc/ssl/certs/"
  - "/etc/sudoers"
  - "/etc/systemd/system/"
  - "/etc/udev/rules.d/"
  - "/lib/modules/"
  - "/lib/systemd/system/"
  - "/lib/udev/rules.d/"
  - "/proc/self/fd/"
  - "/root/.config/"
  - "/root/.kube/config"
  - "/root/.prng/"
  - "/root/.ssh/"
  - "/etc/profile"
  - "/root/.bashrc"
  - "/root/.profile"
  - "/run/udev/rules.d/"
  - "/sys/fs/cgroup"
  - "/sys/module/msr/parameters/allow_writes"
  - "/tmp/cgrp/release_agent"
  - "/tmp/cgrp/x/notify_on_release"
  - "/usr/bin/docker-runc"
  - "/usr/bin/runc"
  - "/usr/lib/modules/"
  - "/usr/lib/systemd/system/"
  - "/usr/lib/udev/rules.d/"
  - "/usr/lib/x86_64-linux-gnu/"
  - "/usr/local/lib/udev/rules.d/"
  - "/usr/sbin/runc"
  - "/var/run/secrets/eks.amazonaws.com/serviceaccount/"
  - "/var/run/utmp"
  - "/var/spool/cron/"
  - "/run/docker.sock"
  - "/run/containerd"
  - "/custom/containerd"
  - "/var/run/docker.sock"
  - "/var/run/containerd"
  - "/custom/containerd"
  #modify binary dirs
  - "/bin"
  - "/sbin"
  - "/usr/bin"
  - "/usr/sbin"
  - "/usr/local/bin"
  - "/usr/local/sbin"
  - "/lib"
  - "/lib64"
  - "/usr/lib"
  - "/usr/lib64"
  - "/usr/local/lib"
  - "/usr/local/lib64"
  - "/etc/profile"
  - "/etc/bash.bashrc"
  - "/etc/zshrc"
  - "/etc/zprofile"
  - "/etc/csh.cshrc"
  - "/etc/ksh.kshrc"
  - "/root/.bashrc"
  - "/root/.profile"
  - "/root/.bash_profile"
  - "/root/.bash_login"
  - "/root/.zshrc"
  - "/root/.zprofile"
  - "/root/.zlogin"
  - "/root/.cshrc"
  - "/root/.tcshrc"
  - "/root/.kshrc"