apiVersion: qualys.com/v1
kind: FimPolicy
metadata:
 name: monitor-file-read
spec:
 base-policy: "file-read"
 action: "audit"
 monitor-paths:
  - "/etc/passwd"
  - "/etc/shadow"
  - "/.git"
  - "/app/.git"
  - "/usr/src/app/.git"
  - "/root/.git"
  - /etc/apache2/
  - /etc/httpd/
  - /etc/nginx/
  - /usr/local/etc/
  - /var/www/html/
  - /etc/secrets/
#  - /run/secrets/
  - /secrets/
  - /.env
  - /app/
  - /srv/
  - /var/lib/jenkins/
  - /opt/sonarqube/conf/
  - /var/atlassian/application-data/confluence/
  - /.docker/
  - /kaniko/.docker/
  - /.npmrc
  - /.pypirc
  - /.netrc
  - /.git/
  - /.ssh/
  - /.git-credentials
  - /root/.git-credentials
  - /root/.ssh/
  - /root/.git/
  - /etc/ansible/
  - /app/.terraform/terraform.tfstate
  - /.terraform/terraform.tfstate
  - /.aws/
  - /.azure/
  - /.config/
  - /etc/ssl/private
  - /etc/letsencrypt/live/
#  - "/proc"
#  - /var/run/secrets/
