apiVersion: v1
kind: Pod
metadata:
  name: compiler-executed-in-container
spec:
  restartPolicy: Never
  containers:
  - name: compiler-executed-in-container
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'gcc -o memfd-exec memfd-exec.c']
