apiVersion: v1
kind: Pod
metadata:
  name: compiler-executed
spec:
  containers:
  - name: compiler-executed
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'gcc -o memfd-exec memfd-exec.c']
