apiVersion: v1
kind: Pod
metadata:
  name: container-resource-abuse
spec:
  containers:
    - name: container-resource-abuse
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
