apiVersion: v1
kind: Pod
metadata:
  name: container-resource-abuse
spec:
  containers:
    - name: container-resource-abuse
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', 'stress --cpu 2 --io 1 --vm 1 --vm-bytes 128M --timeout 600s']
