apiVersion: v1
kind: Pod
metadata:
  name: container-escape-cgroup
spec:
  containers:
  - name: container-escape-via-cgroup
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'unshare -UrmC bash; mount -t cgroup -o memory cgroup /mnt']
