apiVersion: v1
kind: Pod
metadata:
  name: credential-access-bash-history
spec:
  containers:
  - name: credential-access-bash-history
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'cat /.bash_history; rm /.zsh_history']
