#command: TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/

apiVersion: v1
kind: Pod
metadata:
  name: curl-using-socks-proxy
spec:
  containers:
  - name: curl-using-socks-proxy
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'curl -x socks4://proxy.example.com http://www.example.com/']
