apiVersion: v1
kind: Pod
metadata:
  name: db-program-spawned-process
spec:
  containers:
  - name: db-program-spawned-process
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'cp /bin/bash mysqld; ./mysqld -c whoami']
