apiVersion: v1
kind: Pod
metadata:
  name: debugfs-launch
spec:
  containers:
  - name: debugfs-launch
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'debugfs']
