apiVersion: v1
kind: Pod
metadata:
  name: file-made-executable-via-chmod-inside-a-container
spec:
  containers:
  - name: clear-system-logs
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'chmod 4755 memfd-exec; chmod +x memfd-exec']
