apiVersion: v1
kind: Pod
metadata:
  name: file-made-executable-via-chmod-inside-a-container
spec:
  restartPolicy: Never
  containers:
  - name: file-made-executable-via-chmod-inside-a-container
    image: angelrita/base-ubuntu:latest
    command: ['sh']
    args: ['-c', 'chmod 4755 memfd-exec; chmod +x memfd-exec']
