apiVersion: v1
kind: Pod
metadata:
  name: file-made-executable-via-chmod-inside-a-container-copy
spec:
  containers:
  - name: file-made-executable-via-chmod-inside-a-container-copy
    image: angelrita/base-ubuntu:latest
    command: ['sh']
    args: ['-c', 'chmod 4755 memfd-exec; chmod +x memfd-exec']
