apiVersion: v1
kind: Pod
metadata:
  name: gdb-executed-in-container
spec:
  containers:
  - name: gdb-executed-in-container
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'gdb ./memfd-exec']
