apiVersion: v1
kind: Pod
metadata:
  name: insmod-modprobe
spec:
  containers:
  - name: insmod-modprobe
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'modprobe br_netfilter;insmod br_netfilter;sleep infinity']
