apiVersion: v1
kind: Pod
metadata:
  name: interactive-shell-spawned-in-container
spec:
  containers:
  - name: interactive-shell-spawned-in-container
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'sh -i']
