apiVersion: v1
kind: Pod
metadata:
  name: k8s-printenv-execution
spec:
  containers:
    - name: k8s-printenv-execution
      image: angelrita/base-ubuntu:latest
      command: ['sh']
      args: ['-c', '']
