apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-service-account-token-created-in-container
spec:
  restartPolicy: Never
  containers:
  - name: kubernetes-service-account-token-created-in-container
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'kubectl create serviceaccount my-serviceaccount']
