apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
spec:
  containers:
  - name: kube-proxy
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'cp /bin/bash /tmp/kube-proxy; /tmp/kube-proxy -c tcpdump']
