
apiVersion: v1
kind: Pod
metadata:
  name: remote-file-copy-tools
spec:
  containers:
  - name: remote-file-copy-tools
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'scp test@10.113.107.226:/home/Downloads/test.png .']