apiVersion: v1
kind: Pod
metadata:
  name: launch-ingress-remote-file-copy-tools-in-container
spec:
  restartPolicy: Never
  containers:
  - name: launch-ingress-remote-file-copy-tools-in-container
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ["-c", "curl --location --request GET 'https://go.microsoft.com/fwlink/?linkid=2108834&Channel=Stable&language=en' --output foo.exe"]