apiVersion: v1
kind: Pod
metadata:
  name: ingress-remote-file-copy-tools
spec:
  containers:
  - name: ingress-remote-file-copy-tools
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ["-c", "curl --location --request GET 'https://go.microsoft.com/fwlink/?linkid=2108834&Channel=Stable&language=en' --output foo.exe"]