apiVersion: v1
kind: Pod
metadata:
  name: launch-remote-file-copy-tools-in-container
spec:
  restartPolicy: Never
  containers:
  - name: launch-remote-file-copy-tools-in-container
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'scp test@10.113.107.226:/home/Downloads/test.png .']
