apiVersion: v1
kind: Pod
metadata:
  name: local-account-passwd
spec:
  containers:
  - name: local-account-passwd
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'passwd']
