apiVersion: v1
kind: Pod
metadata:
  name: network-utility-executed
spec:
  containers:
  - name: network-utility-executed
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'tcpdump']
