apiVersion: v1
kind: Pod
metadata:
  name: package-management-process-in-container
spec:
  restartPolicy: Never
  containers:
  - name: package-management-process-in-container
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'apt install tcpdump']
