apiVersion: v1
kind: Pod
metadata:
  name: package-installed-in-containe
spec:
  containers:
  - name: package-installed-in-containe
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'apt install tcpdump']
