apiVersion: v1
kind: Pod
metadata:
  name: potential-pri-esc-via-enlightenment
spec:
  containers:
  - name: potential-pri-esc-via-enlightenment
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    #args: ['-c', 'cp /bin/bash /tmp/testbash; sudo setcap cap_sys_ptrace+ep /tmp/testbash; sudo -u test /tmp/testbash -c whoami; sleep infinity']
