apiVersion: v1
kind: Pod
metadata:
  name: prv-esc-process-cap
spec:
  containers:
  - name: prv-esc-process-cap
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'echo "yet to be implemented"; sleep infinity']
