apiVersion: v1
kind: Pod
metadata:
  name: prv-esc-suid-binary
spec:
  containers:
  - name: prv-esc-suid-binary
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'sudo -u test bash -c "passwd"; sleep infinity']
