apiVersion: v1
kind: Pod
metadata:
  name: clear-system-logs
spec:
  containers:
  - name: clear-system-logs
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'su test; passwd; sleep infinity']
