apiVersion: v1
kind: Pod
metadata:
  name: prv-esc-process-cap
spec:
  containers:
  - name: prv-esc-process-cap
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'cp /bin/bash /tmp/testbash; setcap cap_setgid,cap_setuid+ep /tmp/testbash; sudo -u test /tmp/testbash -c whoami; sleep infinity']
