apiVersion: v1
kind: Pod
metadata:
  name: Process-hidden-using-mount
spec:
  containers:
  - name: Process-hidden-using-mount
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'mount -o remount,hidepid=2 /proc']
