apiVersion: v1
kind: Pod
metadata:
  name: ssh-process-launched-from-inside-a-container
spec:
  containers:
  - name: clear-system-logs
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'ssh root@10.113.107.226;']