apiVersion: v1
kind: Pod
metadata:
  name: steganografy-tools
spec:
  containers:
  - name: steganografy-tools
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'steghide embed -cf -ef secret.txt test.jpg']
