apiVersion: v1
kind: Pod
metadata:
  name: sudoedit-privesc
spec:
  containers:
  - name: sudoedit-privesc
    image: chenaotian/cve-2021-3156:latest
    #imagePullPolicy: Never
    command: ["sh"]
    args: ['-c', 'cd ~/exp; sudo -u test bash -c "./exp; whoami > whoami.txt"; sleep infinity']
