apiVersion: v1
kind: Pod
metadata:
  name: test-crypto-miner1
spec:
  containers:
  - name: test-crypto-miner1
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ["/bin/sh"]
    args: ['-c', '/sbin/modprobe msr allow_writes=on > /dev/null 2>&1']