apiVersion: v1
kind: Pod
metadata:
  name: Container Resource Abuse
spec:
  containers:
  - name: usage-of-steganography-tools
    image: angelrita/base-ubuntu:latest
    #imagePullPolicy: Never
    command: ['sh']
    args: ['-c', 'steghide embed -cf -ef secret.txt test.jpg']
